### ISSUE TITLE
请问如何集成到walk或gotk3?

### ISSUE THREAD

**Issue by bianweiall** [nvsoft/cef#1]
非常感谢，已经编译成功，但是不知道如何集成到walk和gotk3，
func CreateBrowser(hwnd unsafe.Pointer, browserSettings *BrowserSettings, url string, offscreenRendering bool) (browser *Browser)
请问函数的第一个参数hwnd具体表示什么？是walk/gotk3的window对象吗？但是类型不一样啊

**Comment by f0cii** [comment]
请参考github.com/nvsoft/gapp，这个项目就是集成了walk的依赖库win。
