### ISSUE TITLE
SendProcessMessage and C.PID_BROWSER

### ISSUE THREAD

**Issue by z505** [nvsoft/cef#3]
When using browser.SendProcessMessage in another package, PID_BROWSER should be accessible from GoLang and not just C.PID_BROWSER maybe?

I am trying to figure out how to send in PID_BROWSER from another package outside of cef...

Maybe a golang wrapper around C.PID_BROWSER you have already made somewhere? I cannot find it. 

I.e. something like this:
    browser.SendProcessMessage(BrowserID, message)

Instead of:
    browser.SendProcessMessage(C.PID_BROWSER, message.CStruct)

Maybe you did not initially intend SendProcessMessage to be used outside of the cef package?

**Comment by f0cii** [comment]
In the Browser process.

You can use like this (in browser.go):
func (b Browser) SendProcessMessageTest() {
	// PID_BROWSER, PID_RENDERER
	message := CefProcessMessageCreate(kV8EvalMessage)
	valueList := message.GetArgumentList()
	s := `function() { return 10; }();`
	//valueList.SetInt(0, 10)
	valueList.SetString(0, s)
	b.SendProcessMessage(C.PID_RENDERER, message.CStruct)
}

In render process.
Code like this(in render_process.go):

b.SendProcessMessage(C.PID_BROWSER, message.CStruct)

Hope that these are useful to you!
